### ISSUE TITLE
Test - Missing test-driver.template.f90

### ISSUE THREAD

**Issue by HandleTBC** [BristolCompositesInstitute/abaci#4]
When executing `abaci test`, unhandled error on attempt to open `test-driver.template.f90`.

Attempt to access `<install_location>/abaci/fortran/test-driver.template.f90`

Inspection of install directory shows: `<install location>/abaci/` directory does not have `fortran` dir or lower. 

Reading of `gen_test_driver()` expects existence of this file. Possibly missing from repo? No conflict with .gitignore file though.

Running on WSL, BCI laptop.

**Comment by LKedward** [comment]
Thanks for reporting - looks like I forgot to update the installer to include the template.
Not sure about that link error however - does it say which symbols are missing?

**Comment by LKedward** [comment]
@HandleTBC - one limitation of the test driver at the moment is that it cannot link to Abaqus-provided subroutines such as `vgetoutdir`, `vgetnumcpus` etc. The current work around for this is to write dummy versions in your test module. A long term solution is for Abaci to provide dummy versions of these subroutines.

**Comment by LKedward** [comment]
@HandleTBC - ah yes you're right, abaci is linking the test driver to both the single and double precision libraries. I've opened a separate issue to track that.

**Comment by HandleTBC** [comment]
Magic, thanks Laurence.
